version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3301:3306
  esnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: esnode1
    environment:
      - node.name=esnode1
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=esnode1,esnode2
      - discovery.seed_hosts=esnode2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode1_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic_network
  esnode2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: esnode2
    environment:
      - node.name=esnode2
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=esnode1,esnode2
      - discovery.seed_hosts=esnode1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode2_data:/usr/share/elasticsearch/data
    networks:
      - elastic_network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://esnode1:9200
    ports:
      - 5601:5601
    depends_on:
      - esnode1
    networks:
      - elastic_network
volumes:
  db:
    driver: local
  esnode1_data:
    driver: local
  esnode2_data:
    driver: local
networks:
  elastic_network:
    driver: bridge